"""
Pipeline KPI Metrics Module.

Computes the four key performance indicators (KPIs) used to assess pipeline
health and dataset quality for the DRC Insight 46 curation workflow.

The four KPIs match those presented in the interview presentation and
can be emitted as JSON for dashboard integration or DMP reporting.

---

**KPI 1 — BIDS Validation Rate**
    % of NIfTI files following BIDS naming conventions (sub-*, .nii.gz,
    JSON sidecars present).
    Target: 100%.  Gating metric — no session enters fMRIPrep or
    FreeSurfer until it passes. "Validation should fail ingestion, not
    be a post-hoc task."

**KPI 2 — Checksum Match Rate**
    % of files whose SHA-256 hash matches the transfer_manifest.json
    recorded at source.
    Target: 100%.  Detects silent data corruption on the route to
    DPUK, GAAIN, or Skylark. Requires a manifest generated by
    verify.generate_manifest() before the transfer.

**KPI 3 — FAIR Compliance Score**
    % of FAIR checks (Findable / Accessible / Interoperable / Reusable)
    passed by the dataset.
    Produced per dataset release; required before DPUK submission and
    Alzheimer's Association data-sharing reporting.

**KPI 4 — Metadata Completeness**
    % of NIfTI sessions (subject × modality) that have a complete JSON
    sidecar alongside the .nii.gz file.
    Missing sidecars mean missing acquisition parameters — critical for
    Insight 46 Phase 3 QSM and dual-tracer PET protocols where
    RepetitionTime and tracer metadata are non-optional.

---

Usage::

    from pathlib import Path
    from neuro_curation.metrics import compute_metrics, format_metrics_report
    import json

    m = compute_metrics(Path("bids_dataset/"))
    print(format_metrics_report(m))

    # Save as JSON for dashboard or DMP integration:
    Path("pipeline_metrics.json").write_text(json.dumps(m, indent=2))
"""

import json
from datetime import datetime, timezone
from pathlib import Path

from neuro_curation.audit import run_audit
from neuro_curation.verify import verify_manifest


# ---------------------------------------------------------------------------
# Individual KPI computations
# ---------------------------------------------------------------------------


def _bids_validation_rate(dataset_dir: Path) -> dict:
    """Check what fraction of NIfTI files comply with BIDS naming rules.

    BIDS requires that every NIfTI file:
    - Is compressed (.nii.gz, not .nii)
    - Lives under a sub-<label>/ directory
    - Has a corresponding JSON sidecar

    We compute three sub-metrics and combine them into a single rate:
    - compression_rate: % of all NIfTI files that are .nii.gz
    - naming_rate:      % of .nii.gz files under a sub-<label>/ directory
    - sidecar_rate:     % of .nii.gz files with a matching .json sidecar

    The overall BIDS validation rate is the minimum of the three, because
    a dataset that is 100% compressed but only 80% named correctly is not
    a 90% valid dataset — it has 20% invalid files.

    Args:
        dataset_dir: Root of the BIDS dataset.

    Returns:
        Dict with rate (0–100), sub-metrics, and per-file details.
    """
    nii_gz = list(dataset_dir.rglob("*.nii.gz"))
    # Uncompressed NIfTI files (*.nii but not *.nii.gz)
    nii_raw = [f for f in dataset_dir.rglob("*.nii") if not str(f).endswith(".nii.gz")]

    total_nifti = len(nii_gz) + len(nii_raw)

    if total_nifti == 0:
        return {
            "rate": None,
            "note": "No NIfTI files found in dataset",
            "files_checked": 0,
        }

    # Sub-metric 1: compression (all NIfTI must be .nii.gz)
    compression_rate = len(nii_gz) / total_nifti * 100 if total_nifti > 0 else 0

    # Sub-metric 2: BIDS naming (must be under sub-<label>/ directory)
    bids_named = [f for f in nii_gz if "sub-" in f.as_posix()]
    naming_rate = len(bids_named) / len(nii_gz) * 100 if nii_gz else 0

    # Sub-metric 3: JSON sidecar coverage (every .nii.gz needs a .json)
    has_sidecar = [
        f for f in nii_gz
        if f.with_suffix("").with_suffix(".json").exists()
    ]
    sidecar_rate = len(has_sidecar) / len(nii_gz) * 100 if nii_gz else 0

    # Overall rate = minimum of the three (weakest link)
    overall_rate = min(compression_rate, naming_rate, sidecar_rate)

    return {
        "rate": round(overall_rate, 1),
        "files_checked": total_nifti,
        "nii_gz_files": len(nii_gz),
        "nii_raw_files": len(nii_raw),
        "sub_metrics": {
            "compression_rate": round(compression_rate, 1),
            "bids_naming_rate": round(naming_rate, 1),
            "sidecar_rate": round(sidecar_rate, 1),
        },
        "target": 100.0,
        "target_met": overall_rate >= 100.0,
    }


def _checksum_match_rate(dataset_dir: Path) -> dict:
    """Verify file integrity against the transfer manifest.

    Calls verify_manifest() and converts the pass/fail file counts into
    a percentage rate.  Requires a transfer_manifest.json generated by
    verify.generate_manifest() *before* the transfer.

    If no manifest exists, rate is None (not 0 — absence of evidence is
    not evidence of corruption, but we flag it clearly).

    Args:
        dataset_dir: Root of the BIDS dataset.

    Returns:
        Dict with rate (0–100 or None), file counts, and issue lists.
    """
    result = verify_manifest(dataset_dir)

    if "error" in result:
        return {
            "rate": None,
            "note": result["error"],
            "files_checked": 0,
        }

    total = result["total_files"]
    passed = result["files_checked"] - len(result["mismatches"])
    rate = passed / total * 100 if total > 0 else 100.0

    return {
        "rate": round(rate, 1),
        "files_checked": total,
        "files_passed": passed,
        "mismatches": len(result["mismatches"]),
        "missing": len(result["missing"]),
        "target": 100.0,
        "target_met": result["passed"],
        "mismatch_paths": [m["path"] for m in result["mismatches"]],
        "missing_paths": result["missing"],
    }


def _fair_score(dataset_dir: Path) -> dict:
    """Compute FAIR compliance score from audit module.

    Runs the full FAIR audit and returns the per-principle breakdown
    alongside the overall score.

    Args:
        dataset_dir: Root of the BIDS dataset.

    Returns:
        Dict with score (0–100), per-principle breakdown, and check details.
    """
    audit = run_audit(dataset_dir)

    per_principle = {}
    for code, data in audit["principles"].items():
        per_principle[code] = {
            "passed": data["passed"],
            "total": data["total"],
            "rate": round(data["passed"] / data["total"] * 100, 1) if data["total"] > 0 else 0,
        }

    return {
        "rate": audit["score"],
        "total_passed": audit["total_passed"],
        "total_checks": audit["total_checks"],
        "per_principle": per_principle,
        "target": 80.0,   # 80% = required for DPUK submission; 100% = ideal
        "target_met": audit["score"] >= 80.0,
    }


def _metadata_completeness(dataset_dir: Path) -> dict:
    """Compute what fraction of NIfTI files have a complete JSON sidecar.

    A "complete" sidecar is one that exists and contains at least the
    mandatory acquisition fields for neuroimaging:
    - MRI: RepetitionTime and EchoTime (essential for group-level analysis)
    - PET: TracerName and InjectedRadioactivity (per PET-BIDS standard,
      Nørgaard et al. 2022)

    If a sidecar exists but lacks mandatory fields, the session is flagged
    as "incomplete" rather than "missing" so we can distinguish data
    quality issues from pipeline failures.

    Args:
        dataset_dir: Root of the BIDS dataset.

    Returns:
        Dict with rate (0–100), session counts, and lists of issues.
    """
    # Mandatory sidecar fields by modality (BIDS spec minimums)
    MANDATORY_FIELDS = {
        # MRI anatomical / functional
        "T1w":    [],   # No mandatory fields beyond file existence
        "T2w":    [],
        "bold":   ["RepetitionTime"],
        "flair":  [],
        # MRI quantitative (Phase 3 QSM protocol)
        "T2starw": ["EchoTime"],
        "TB1map":  [],
        # PET (PET-BIDS, Nørgaard et al. 2022)
        "pet":    ["TracerName", "InjectedRadioactivity"],
    }

    nii_gz = list(dataset_dir.rglob("*.nii.gz"))
    if not nii_gz:
        return {
            "rate": None,
            "note": "No NIfTI files found",
            "files_checked": 0,
        }

    complete = []
    incomplete = []   # Sidecar exists but missing mandatory fields
    missing_sidecar = []

    for nii in nii_gz:
        sidecar = nii.with_suffix("").with_suffix(".json")

        if not sidecar.exists():
            missing_sidecar.append(nii.name)
            continue

        # Parse sidecar JSON
        try:
            meta = json.loads(sidecar.read_text())
        except json.JSONDecodeError:
            incomplete.append({"file": nii.name, "issue": "invalid JSON"})
            continue

        # Determine modality from filename (last suffix before .nii.gz)
        stem = nii.name.replace(".nii.gz", "")
        modality = stem.split("_")[-1] if "_" in stem else stem

        # Check mandatory fields for this modality
        required = MANDATORY_FIELDS.get(modality, [])
        missing_fields = [f for f in required if f not in meta]

        if missing_fields:
            incomplete.append({
                "file": nii.name,
                "issue": f"missing fields: {', '.join(missing_fields)}",
            })
        else:
            complete.append(nii.name)

    total = len(nii_gz)
    passed = len(complete)
    rate = passed / total * 100 if total > 0 else 0

    return {
        "rate": round(rate, 1),
        "files_checked": total,
        "files_complete": passed,
        "files_incomplete": len(incomplete),
        "files_missing_sidecar": len(missing_sidecar),
        "target": 100.0,
        "target_met": rate >= 100.0,
        "issues": {
            "incomplete": incomplete,
            "missing_sidecar": missing_sidecar,
        },
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def compute_metrics(dataset_dir: Path) -> dict:
    """Compute all four pipeline KPIs for a BIDS dataset.

    This is the main public function. It runs all four KPI checks and
    packages them into a single structured report suitable for:
    - Printing as a text dashboard (format_metrics_report)
    - Saving as JSON for dashboard integration or DMP evidence

    Args:
        dataset_dir: Root of the BIDS dataset (or curation output directory).

    Returns:
        Dict with top-level summary and per-KPI detail sections.
        Keys: dataset, generated_at, summary, kpis
    """
    dataset_dir = Path(dataset_dir)

    bids_rate = _bids_validation_rate(dataset_dir)
    checksum_rate = _checksum_match_rate(dataset_dir)
    fair = _fair_score(dataset_dir)
    completeness = _metadata_completeness(dataset_dir)

    # Summary: how many KPIs met their targets?
    kpi_results = [bids_rate, checksum_rate, fair, completeness]
    targets_met = sum(1 for k in kpi_results if k.get("target_met") is True)
    targets_na = sum(1 for k in kpi_results if k.get("rate") is None)

    return {
        "dataset": str(dataset_dir),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": {
            "kpis_total": 4,
            "kpis_target_met": targets_met,
            "kpis_unavailable": targets_na,
        },
        "kpis": {
            "bids_validation_rate": bids_rate,
            "checksum_match_rate": checksum_rate,
            "fair_compliance_score": fair,
            "metadata_completeness": completeness,
        },
    }


def format_metrics_report(metrics: dict) -> str:
    """Format KPI metrics as a human-readable dashboard report.

    Args:
        metrics: Output from compute_metrics().

    Returns:
        Multi-line formatted string with per-KPI rows and a summary.
    """
    KPI_LABELS = {
        "bids_validation_rate":  "BIDS Validation Rate     ",
        "checksum_match_rate":   "Checksum Match Rate      ",
        "fair_compliance_score": "FAIR Compliance Score    ",
        "metadata_completeness": "Metadata Completeness    ",
    }

    lines = [
        "=== neuro-curation Pipeline Metrics ===",
        f"Dataset : {metrics['dataset']}",
        f"Run at  : {metrics['generated_at']}",
        "",
        f"{'KPI':<30}  {'Rate':>7}  {'Target':>8}  Status",
        "-" * 62,
    ]

    for key, label in KPI_LABELS.items():
        kpi = metrics["kpis"][key]
        rate = kpi.get("rate")
        target = kpi.get("target")
        met = kpi.get("target_met")

        rate_str   = f"{rate:.1f}%" if rate is not None else "   N/A"
        target_str = f"{target:.0f}%" if target is not None else "    —"
        status_str = "PASS" if met is True else ("FAIL" if met is False else "N/A")

        lines.append(f"{label}  {rate_str:>7}  {target_str:>8}  {status_str}")

    summary = metrics["summary"]
    lines += [
        "-" * 62,
        f"KPIs meeting target: {summary['kpis_target_met']} / "
        f"{summary['kpis_total'] - summary['kpis_unavailable']} available",
        "",
    ]

    # Per-KPI detail for failing metrics
    for key, label in KPI_LABELS.items():
        kpi = metrics["kpis"][key]
        if kpi.get("target_met") is False:
            lines.append(f"[Detail] {label.strip()}")
            issues = kpi.get("issues", {})
            missing_s = issues.get("missing_sidecar", [])
            incomplete = issues.get("incomplete", [])
            mismatches = kpi.get("mismatch_paths", [])
            missing_f  = kpi.get("missing_paths", [])
            if missing_s:
                lines.append(f"  Missing sidecars ({len(missing_s)}):")
                for p in missing_s[:5]:
                    lines.append(f"    {p}")
                if len(missing_s) > 5:
                    lines.append(f"    … and {len(missing_s) - 5} more")
            if incomplete:
                lines.append(f"  Incomplete sidecars ({len(incomplete)}):")
                for item in incomplete[:5]:
                    lines.append(f"    {item['file']} — {item['issue']}")
                if len(incomplete) > 5:
                    lines.append(f"    … and {len(incomplete) - 5} more")
            if mismatches:
                lines.append(f"  Hash mismatches ({len(mismatches)}):")
                for p in mismatches[:5]:
                    lines.append(f"    {p}")
            if missing_f:
                lines.append(f"  Missing files ({len(missing_f)}):")
                for p in missing_f[:5]:
                    lines.append(f"    {p}")
            lines.append("")

    return "\n".join(lines)
